application: simple-prosthetic
version: 1

runtime: python27
api_version: 1
threadsafe: false

builtins:
- admin_redirect: on
- datastore_admin: on
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /static
  static_dir: static
  expiration: 1h
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: 365d

- url: /defer/.*
  script: handlers.deferred.app
  login: admin

- url: /admin/.*
  script: handlers.admin.app
  login: admin

- url: /.*
  script: handlers.frontend.app

- url: /_ah/warmup
  script: handlers.warmup.app
