application: simple-prosthetic
version: 1

runtime: python27
api_version: 1
threadsafe: true

builtins:
- admin_redirect: on
- datastore_admin: on
- remote_api: on

handlers:
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /defer/.*
  script: handlers.deferred.app
  login: admin

- url: /backend/.*
  script: handlers.backend.app
  login: admin

- url: /admin/.*
  script: handlers.admin.app
  login: admin

- url: /.*
  script: handlers.frontend.app
